---
services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./certs:/app/certs
    restart: unless-stopped
    logging: &logging
      driver: journald
      options:
        tag: '{% raw %}{{.Name}}{% endraw %}'

  pylon:
    image: backenddevelopersltd/bittensor-pylon:latest
    environment:
      BITTENSOR_NETUID: 1
      BITTENSOR_NETWORK: ws://54.83.169.218:9946
      BITTENSOR_WALLET_PATH: ~/.bittensor/wallets
      BITTENSOR_WALLET_NAME: extra_validator_1
      BITTENSOR_WALLET_HOTKEY_NAME: default
    volumes:
      - ./db:/app/db
      - $HOME/.bittensor:/root/.bittensor
    restart: unless-stopped
    logging:
      <<: *logging

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/config_helpers:/etc/nginx/config_helpers:ro
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      auth:
        condition: service_started
    restart: unless-stopped
    command: [ "/bin/sh", "-c", "/etc/nginx/config_helpers/generate_cert.sh && nginx -g 'daemon off;'" ]
    logging:
      <<: *logging
